[tools]
# C/C++ Tools
cmake = "latest"
ninja = "latest"

# Go Tools
go = "latest"

# Java Tools
java = "latest"

# Python Tools
python = ["latest", "3.14"]
ruff = "latest"
ty = "latest"
uv = "latest"

# Javascript/Typescript Tools
"npm:typescript" = "latest"
bun = "latest"
node = "22"

# Rust Tools
rust = "latest"

# Other CLI Tools
fd = "latest"
gh = "latest"
neovim = "nightly"
ripgrep = "latest"
tree-sitter = "latest"

# LSP Servers & Formatters
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
jq = "latest"
lua-language-server = "latest"
shellcheck = "latest"
stylua = "latest"
taplo = "latest"
